### ISSUE TITLE
Error on open index.html

### ISSUE THREAD

**Issue by TorchwoodPL** [kevinhikaruevans/uojs2#23]
I clone git and done everything with npm an gulp. I run and get:

> [root@pol webClient]# npm start
> 
> > uojs2@0.0.1 start /var/www/html/webClient
> > node dist/server/server.js
> 
> WebSocket settings:
> 
>     - proxying from :2595 to pol.hell-yeah.eu:2593
>     - Running in unencrypted HTTP (ws://) mode
> 
> (node:19736) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

After going from browser to index.html I get:

> Download the React DevTools for a better development experience: https://fb.me/react-devtools
> three.js:24833THREE.WebGLRenderer 79
> dev-server.js:60[HMR] Waiting for update signal from WDS...
> http://127.0.0.1:4000/sockjs-node/info?t=1476273420303 Failed to load resource: net::ERR_CONNECTION_REFUSED
> client?ce4f:41[WDS] Disconnected!log @ client?ce4f:41
> http://127.0.0.1:4000/sockjs-node/info?t=1476273421510 Failed to load resource: net::ERR_CONNECTION_REFUSED
> abstract-xhr.js:132 GET http://127.0.0.1:4000/sockjs-node/info?t=1476273424560 net::ERR_CONNECTION_REFUSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21

in chrome console, can somebody tell me how to fix it?

Cheers!

**Comment by kevinhikaruevans** [comment]
It's hardcoded to use port 2594 instead of 2595 right now. You might be able to edit src/client/network/gamesocket.js to update that.

**Comment by TorchwoodPL** [comment]
And what about:

> Download the React DevTools for a better development experience: https://fb.me/react-devtools
> three.js:24833THREE.WebGLRenderer 79
> dev-server.js:60[HMR] Waiting for update signal from WDS...
> abstract-xhr.js:132GET http://127.0.0.1:4000/sockjs-node/info?t=1476302005903 net::ERR_CONNECTION_REFUSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21
> client?ce4f:41[WDS] Disconnected!log @ client?ce4f:41close @ client?ce4f:86sock.onclose @ socket.js:15EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:356
> abstract-xhr.js:132 GET http://127.0.0.1:4000/sockjs-node/info?t=1476302008019 net::ERR_CONNECTION_REFUSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21
> abstract-xhr.js:132 GET http://127.0.0.1:4000/sockjs-node/info?t=1476302011072 net::ERR_CONNECTION_REFUSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21

**Comment by kevinhikaruevans** [comment]
Hmm... that is just the live reload stuff. 

Are you using `gulp build` or `gulp watch`?

**Comment by TorchwoodPL** [comment]
I have only red rectangle on black background when I enter index.html. I use gulp build after every change I mąkę. So this 4000 port error is not important? Can you give some screens what should I see on page?

**Comment by kevinhikaruevans** [comment]
I'd forgotten I commited random stuff into master... Sorry about that. 

Try pulling again and this time run `gulp build-server && gulp dev`, then navigate to http://localhost:4000/

It should look like this:
![image](https://cloud.githubusercontent.com/assets/4730591/19328261/aec5453c-9087-11e6-8ed1-bf3475a2b47e.png)

Then you login and it looks like this:
![image](https://cloud.githubusercontent.com/assets/4730591/19328274/ba2f5764-9087-11e6-93bf-60b7c7b429b2.png)

And after that, nothing really shows up, aside from a debug screen and a yellow box:
![image](https://cloud.githubusercontent.com/assets/4730591/19328279/c879ccdc-9087-11e6-8b3a-e2461435c719.png)

**Comment by TorchwoodPL** [comment]
Now I get:

> [root@pol webClient]# npm start
> 
> > uojs2@0.0.1 start /var/www/webClient
> > node dist/server/server.js
> 
> module.js:457
>     throw err;
>     ^
> 
> Error: Cannot find module '/var/www/webClient/dist/server/server.js'
>     at Function.Module._resolveFilename (module.js:455:15)
>     at Function.Module._load (module.js:403:25)
>     at Module.runMain (module.js:590:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> npm ERR! Linux 2.6.32-042stab113.21
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
> npm ERR! node v6.7.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! uojs2@0.0.1 start: `node dist/server/server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the uojs2@0.0.1 start script 'node dist/server/server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the uojs2 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node dist/server/server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs uojs2
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls uojs2
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/webClient/npm-debug.log
>

**Comment by kevinhikaruevans** [comment]
Did you run gulp build-server first? It just looks like the server file didn't get built.

**Comment by TorchwoodPL** [comment]
Yes I did:

> [root@pol webClient]# gulp build-server
> [16:39:22] Using gulpfile /var/www/webClient/gulpfile.js
> [16:39:22] Starting 'build-server'...
> [16:39:23] Finished 'build-server' after 573 ms
> [root@pol webClient]#

**Comment by kevinhikaruevans** [comment]
Does it create the js file in `dist/server/`?

**Comment by TorchwoodPL** [comment]
After gulp build:

> [root@pol dist]# ls -l
> total 12416
> -rw-r--r-- 1 root root 3028437 Oct 13 16:43 bundle.js
> -rw-r--r-- 1 root root 3662987 Oct 13 16:43 bundle.js.map
> drwxr-xr-x 2 root root    4096 Oct 13 16:43 server
> -rw-r--r-- 1 root root 1207302 Oct 13 16:43 uojs2.min.js
> -rw-r--r-- 1 root root 4802968 Oct 13 16:43 uojs2.min.js.map
> [root@pol dist]#

Then when i run gulp dev insude dist folder I only have index.html and uojs2.js. Rest is deleted :(

**Comment by kevinhikaruevans** [comment]
Is there anything in the server folder? You should be running gulp in the cloned folder.

**Comment by TorchwoodPL** [comment]
> [root@pol webClient]# ls -l ./dist/server
> total 8
> -rw-r--r-- 1 root root  185 Oct 13 16:46 config.js
> -rw-r--r-- 1 root root 1078 Oct 13 16:46 server.js
> [root@pol webClient]#

After gulp build. Where and what cmd I should run?

**Comment by kevinhikaruevans** [comment]
From the webClient directory, try just running node ./dist/server/server.js

**Comment by TorchwoodPL** [comment]
So...

1. Clone repo and change configs for server
2. Run **npm install** in main dir
3. Run **gulp build**
4. From main dir run **node ./dist/server/server.js** in first terminal window
5. From main dir run **npm run** in second terminal window
6. Open **http://localhost:4000/**

Right?

**Comment by TorchwoodPL** [comment]
But when I run gulp dev it removes dist/server dir.... Gulp build creates it, gulp dev removes...

**Comment by kevinhikaruevans** [comment]
Hmmm, weird. Try running gulp dev first, then in a new window, run `gulp build-server`

**Comment by TorchwoodPL** [comment]
Yes it is working, but I cannot log in to POL server :(

**Comment by TorchwoodPL** [comment]
When I try to login I get:

> VM107:37 WebSocket connection to 'ws://127.0.0.1:2594/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSEDWrappedWebSocket @ VM107:37connect @ gamesocket.js:28LoginHandler._this.loginWithCredentials @ login.js:40LoginComponent._this.handleLoginClick @ login.jsx:27ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70executeDispatch @ EventPluginUtils.js:89executeDispatchesInOrder @ EventPluginUtils.js:112executeDispatchesAndRelease @ EventPluginHub.js:44executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:55forEachAccumulated @ forEachAccumulated.js:25processEventQueue @ EventPluginHub.js:231runEventQueueInBatch @ ReactEventEmitterMixin.js:18handleTopLevel @ ReactEventEmitterMixin.js:29handleTopLevelImpl @ ReactEventListener.js:73perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150
> gamesocket.js:44 Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2…}GameSocket.handleError @ gamesocket.js:44
> gamesocket.js:49 socket closed

**Comment by kevinhikaruevans** [comment]
Are you running `node ./dist/server/server.js` in a separate window?

What's the output in that window?

**Comment by TorchwoodPL** [comment]
Yes I am running that, and I get: 

> [root@pol webClient]# npm start
> 
> > uojs2@0.0.1 start /var/www/webClient
> > node dist/server/server.js
> 
> WebSocket settings:
> 
>     - proxying from :2594 to 155.133.43.140:2593
>     - Running in unencrypted HTTP (ws://) mode
> 
> (node:19549) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

And on chrom developer console I teg what I sended above.

**Comment by TorchwoodPL** [comment]
websockify 155.133.43.140:2594 155.133.43.140:2593

I changes frol 127.0.0.1 to ip address and it starts to work. But even if proxy is workin I skill can not log to POL emulator.

**Comment by TorchwoodPL** [comment]
```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
dev-server.js:60[HMR] Waiting for update signal from WDS...
client?9f09:37[WDS] Hot Module Replacement enabled.
gamesocket.js:138 send > [Packet: Unknown 0x34]
gamesocket.js:138 send > [Packet: Login]
gamesocket.js:138 send > [Packet: Unknown 0xa0]
gamesocket.js:49 socket closed
```
AND

```
{
  "login": {
    "user": {
      "loggedIn": false,
      "error": null,
      "username": null,
      "key": null,
      "characters": null,
      "chosenCharacterIndex": null
    },
    "servers": {
      "list": [
        {
          "id": 1,
          "name": "Ancaria\u0001",
          "address": "155.133.43.140"
        }
      ],
      "selected": 0
    },
    "currentServer": {
      "features": 0,
      "sentVersion": null,
      "loginCompleted": false,
      "time": {
        "offset": 0,
        "loginTime": "00:00:00"
      }
    }
  },
  "world": {
    "messages": [],
    "objects": [],
    "map": {
      "id": 0,
      "width": 0,
      "height": 0,
      "x": 0,
      "y": 0
    },
    "weather": {
      "isRaining": false,
      "isSnowing": false,
      "temperature": 0,
      "particles": 0
    },
    "light": {
      "level": 0
    },
    "season": {
      "flag": null,
      "playSound": false
    }
  },
  "player": {
    "health": 0,
    "maxHealth": 0,
    "serial": 0,
    "warMode": false,
    "location": {
      "x": null,
      "y": null,
      "z": null,
      "direction": null
    },
    "body": {
      "id": 400,
      "hue": 0
    }
  },
  "network": {
    "compressed": false,
    "connected": false,
    "reconnecting": false,
    "sentLogin": true,
    "sentRelogin": false,
    "seed": [
      52,
      188,
      109,
      216
    ]
  },
  "ping": {
    "lastPingTime": 0,
    "latency": 0
  }
}
```

After try to log to a server on valid account :)

**Comment by kevinhikaruevans** [comment]
Hmmm... you're using POL as the server right? I'll download that server and take a look at it. I think there's a few minor differences between ServUO & POL's login,

**Comment by kevinhikaruevans** [comment]
I opened up another issue: #24  :)
