### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by TorchwoodPL** [kevinhikaruevans/uojs2#37]
> E:\UltimaOnline\UOJS2>gulp build-server && gulp dev
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module './webpack.config'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (E:\UltimaOnline\UOJS2\gulpfile.js:25:23)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)

Any solution?

**Comment by kevinhikaruevans** [comment]
Sorry, the commands have been updated and I haven't written it up on the readme yet.

If you type in `npm run` it'll have the commands. 

You'll need to run `npm proxy:debug` and `npm development:client` (in two different terminal windows).

**Comment by TorchwoodPL** [comment]
Now I get:

> E:\UltimaOnline\UOJS2>npm run proxy:debug
> 
> > uojs2@0.0.1 proxy:debug E:\UltimaOnline\UOJS2
> > DEBUG=* node src/server
> 
> 'DEBUG' is not recognized as an internal or external command,
> operable program or batch file.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "D:\\Apps\\NodeJS\\node.exe" "D:\\Apps\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "proxy:debug"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! uojs2@0.0.1 proxy:debug: `DEBUG=* node src/server`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the uojs2@0.0.1 proxy:debug script 'DEBUG=* node src/server'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the uojs2 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     DEBUG=* node src/server
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs uojs2
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls uojs2
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     E:\UltimaOnline\UOJS2\npm-debug.log

**Comment by kevinhikaruevans** [comment]
In your terminal window, try entering this as separate commands:

`SET DEBUG=*`

`node src/server`

**Comment by TorchwoodPL** [comment]
yes, that worked

**Comment by TorchwoodPL** [comment]
Now I have:

> E:\UltimaOnline\UOJS2>npm run development:client                                                                  
>                                                                                                                   
> > uojs2@0.0.1 development:client E:\UltimaOnline\UOJS2                                                            
> > webpack-dev-server --config webpack --hot --inline                                                              
>                                                                                                                   
> Project is running at http://localhost:8080/                                                                      
> webpack output is served from http://localhost:8080/                                                              
> Content not from webpack is served from E:\UltimaOnline\UOJS2\public                                              
> Time: 19255ms                                                                                                     
>       Asset     Size  Chunks       Chunk Names                                                                    
> default.cur  2.24 kB                                                                                              
>  intro.webm  3.46 MB                                                                                              
>   bundle.js  8.15 MB       0       main                                                                           
> chunk    {0} bundle.js (main) 2.92 MB [entry] [rendered]                                                          
>     > main [645]                                                                                                  
>                                                                                                                   
> ERROR in ./src/client/network/gamesocket.js                                                                       
> Module build failed: E:/UltimaOnline/UOJS2/src/client/network/gamesocket.js: Duplicate declaration "config"       
>                                                                                                                   
>    6 | console.log(config);                                                                                       
>    7 |                                                                                                            
> >  8 | import config from 'config';                                                                               
>      |        ^                                                                                                   
>    9 |                                                                                                            
>   10 | export class GameSocket {                                                                                  
>   11 |     constructor(store, packetRegistry) {                                                                   
>                                                                                                                   
> BabelLoaderError: E:/UltimaOnline/UOJS2/src/client/network/gamesocket.js: Duplicate declaration "config"          
>                                                                                                                   
>    6 | console.log(config);                                                                                       
>    7 |                                                                                                            
> >  8 | import config from 'config';                                                                               
>      |        ^                                                                                                   
>    9 |                                                                                                            
>   10 | export class GameSocket {                                                                                  
>   11 |     constructor(store, packetRegistry) {                                                                   
>                                                                                                                   
>     at transpile (E:\UltimaOnline\UOJS2\node_modules\babel-loader\lib\index.js:55:13)                             
>     at Object.module.exports (E:\UltimaOnline\UOJS2\node_modules\babel-loader\lib\index.js:138:12)                
>  @ ./src/client/index.js 15:18-49                                                                                 
>  @ multi main                                                                                                     
> webpack: bundle is now VALID.                

Also I have blank page when I enter http://localhost:8080/

My development.json:

> {
>     "dev-server.host"   : "localhost",
>     "dev-server.port"   : 8080,
>     "dev-server.proxy"  : [],
>     "server.host"       : "localhost",
>     "ws.host"           : "localhost",
>     "ws.port"           : 2594,
>     "net.host"          : "localhost",
>     "net.port"          : 2593
> }

**Comment by TorchwoodPL** [comment]
When I change localhost to 127.0.0.1 it stays the same...

**Comment by kevinhikaruevans** [comment]
Try cloning it again now

**Comment by TorchwoodPL** [comment]
Now it is working, you do not fix **npm run proxy:debug** right?

**Comment by lamo2k123** [comment]
fix windows run 
commit: https://github.com/lamo2k123/uojs2/commit/d9643359c516ec7c068eb02cc49054e2b97f295a
pr: https://github.com/kevinhikaruevans/uojs2/pull/39

**Comment by lamo2k123** [comment]
Duplicate declaration "config" fixed
