### ISSUE TITLE
add $REPO_TOKEN env .travis.yml

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uojs2#42]
https://docs.codeclimate.com/v1.0/docs/travis-ci-javascript-test-coverage
https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings

**Comment by lamo2k123** [comment]
code_climate settings

**Comment by kevinhikaruevans** [comment]
I updated the REPO_TOKEN enviroment variable in Travis.

[Page on codeclimate](https://codeclimate.com/github/kevinhikaruevans/uojs2) has been at "Preparing to analyze your code" for a while...

**Comment by kevinhikaruevans** [comment]
Hmm... It doesn't seem to be updating on Codeclimate. Any ideas why?

**Comment by lamo2k123** [comment]
travis log: /home/travis/build.sh: line 57: lcov.info: No such file or directory

**Comment by lamo2k123** [comment]
webpack used eslint & stylelint.
