### ISSUE TITLE
Merge refactoring -> master?

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uojs2#53]
What do you think about it? @kevinhikaruevans

**Comment by kevinhikaruevans** [comment]
Looks really good. Nice work!

Create a PR and I'll take a look at it tonight 👍

**Comment by lamo2k123** [comment]
It should perhaps before the PR bit clean code and old files.

**Comment by kevinhikaruevans** [comment]
Do you want to make the PR?

**Comment by lamo2k123** [comment]
We must first clear the branch refactoring

**Comment by lamo2k123** [comment]
https://github.com/kevinhikaruevans/uojs2/pull/57
