### ISSUE TITLE
Create `status-info` visualization component.

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uojs2#60]
Full: ![status_open](https://cloud.githubusercontent.com/assets/674847/21625232/bdf62500-d21b-11e6-8063-9b7e548ef593.JPG)

Min: ![status_min](https://cloud.githubusercontent.com/assets/674847/21625239/c6429090-d21b-11e6-96f6-fb4734631496.JPG)

**Comment by kevinhikaruevans** [comment]
If we want to use gump images for this, we'll need to wait until [uodatareader](https://github.com/kevinhikaruevans/uodatareader) can serve gump images. Until then, it might be best just to do it all in HTML and CSS.

**Comment by lamo2k123** [comment]
I suggest to all the small UI elements do in CSS and HTML. And to uodatareader apply only to the main window (render scene)

**Comment by lamo2k123** [comment]
where to get information on:
1. hit chance increase
2. defense chance increase
3. lower mana cost
4. Weapon damage increase
5. swing speed increase
6. lower reagent cost
7. spell damage increase
8. faster casting
9. faster cast recovery
10. physical resistance === armorRating?

@kevinhikaruevans help :)

**Comment by lamo2k123** [comment]
hmmm. i find http://docs.polserver.com/packets/index.php?Packet=0x11 flag 6 or higher

**Comment by lamo2k123** [comment]
opsss..

**Comment by kevinhikaruevans** [comment]
Might need to send 0x34 status request with 0x04 type to get 0x11? Not sure

**Comment by lamo2k123** [comment]
I can not find information about the state (up, down, lock) stats (str, dex, int). @kevinhikaruevans

**Comment by kevinhikaruevans** [comment]
I think http://docs.polserver.com/packets/index.php?Packet=0xBF has str/dex/int

**Comment by lamo2k123** [comment]
server does not send subcommand 0x19

**Comment by lamo2k123** [comment]
It may be necessary to first send 'Subcommand b: Client Sent once at login of character.'
