### ISSUE TITLE
Cannot access http://localhost:8080/

### ISSUE THREAD

**Issue by TorchwoodPL** [kevinhikaruevans/uojs2#63]
Howdy!

I pull newest commit from master, don so:

```
E:\UltimaOnline\UOJS2>yarn install
yarn install v0.18.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.34s.

E:\UltimaOnline\UOJS2>yarn run development
yarn run v0.18.1
$ yarn run proxy:debug & yarn run development:client & wait
yarn run v0.18.1
$ node src/server -d=*
```

and after I type http://localhost:8080/ I get 404.

My development.json is:

```
{
    "dev-server.host"   : "127.0.0.1",
    "dev-server.port"   : 8080,
    "dev-server.proxy"  : [],

    "server.host" : "127.0.0.1",
	"net.port"  : 2593,

    "net.timeout" : 5000,

    "ws.client.host" : "127.0.0.1",
    "ws.server.host" : "127.0.0.1",
    "ws.port" : 2594
}
```

I added "net.port"  : 2593, to id because there was no net.port in newest dev json pulled from repo. Dunno why, maybe you guys harcoded it, but even with net.pot in the file still page get 404.

**Comment by lamo2k123** [comment]
Windows CLI It is not supported by the '&'. You need to run a separate command. 
Run: 
1) yarn run proxy:debug
2) yarn run development:client

**Comment by lamo2k123** [comment]
fsevents optional package and only works on macos

**Comment by lamo2k123** [comment]
working? @TorchwoodPL

**Comment by kevinhikaruevans** [comment]
Should we use https://www.npmjs.com/package/concurrently for better crossplatform support?

**Comment by lamo2k123** [comment]
early after stopping concurrently process, child processes left in the zombie. it is necessary to check whether the package is now working correctly.

**Comment by TorchwoodPL** [comment]
Yeap it is working :)
