### ISSUE TITLE
SUPPORT

### ISSUE THREAD

**Issue by 3HMonkey** [kevinhikaruevans/uojs2#89]
Hey guys. I have been a programmer or server developer for uo/runuo/etc for more than 10 years and really like this project.Maybe I can support you. Am I able to contact you?

**Comment by ghost-458** [comment]
Hey! Feel free to email me (kevin.h.evans@wsu.edu) or write issues on here. I'm incredibly busy right now but I'll try to respond to things within a day or two. 

If you want to make any changes, feel free to do a PR and I'll get it merged in.
